### ISSUE TITLE
Translation of repeated elements

### ISSUE THREAD

**Issue by alpin3rocker** [tritum/repeatable_form_elements#43]
Hi,
i use version/4.x.x and Typo3 12.4.17
1. What is the trick to get the translation of the repeated field/label element from e.g. de.locallang.xlf?

`<trans-unit id="element.repeatablecontainer-1.number-1.properties.label" approved="yes">
    <source>Translation</source>
    <target>Überstzung</target>
</trans-unit>`
`
<trans-unit id="element..number-1.properties.label" approved="yes">
     <source>Translation</source>
     <target>Übersetzung</target>
</trans-unit>`

both does not work.

2. A label with a dynamic counter prepend or append for each repeated container would be nice e.g.:
Person 1
Person 2
Person 3
...

Thank you for answer

**Comment by chrosey** [comment]
Thank you for your request. It would be a nice improvement to use translations from the parent element (possibly even with dynamic count).

As in the current state of the extension, you would need to do something like the following:
`issue-43.form.yaml`
```yaml
renderingOptions:
  submitButtonLabel: Submit
type: Form
identifier: issue-43
label: issue-43
prototypeName: standard
renderables:
  -
    renderingOptions:
      previousButtonLabel: 'Previous step'
      nextButtonLabel: 'Next step'
    type: Page
    identifier: page-1
    label: Step
    renderables:
      -
        defaultValue: ''
        type: Text
        identifier: Example
        label: ExampleTest
      -
        properties:
          minimumCopies: '1'
          maximumCopies: 10
          showRemoveButton: true
          copyButtonLabel: Copy
          removeButtonLabel: Remove
        type: RepeatableContainer
        identifier: RepeatableContainer-1
        label: RepeatableContainerTest
        renderables:
          -
            defaultValue: ''
            type: Text
            identifier: Person
            label: PersonTest
  -
    renderingOptions:
      previousButtonLabel: 'Previous step'
      nextButtonLabel: 'Next step'
    type: SummaryPage
    identifier: summarypage-1
    label: 'Summary step'

```

`EXT:site_package/Configuration/Yaml/FormSetup.yaml`
```yaml
TYPO3:
  CMS:
    Form:
      prototypes:
        standard:
          formElementsDefinition:
            Form:
              renderingOptions:
                translation:
                  translationFiles:
                    1723196345: 'EXT:site_package/Resources/Private/Language/issue-43.xlf'
```                    

`EXT:site_package/Resources/Private/Language/issue-43.xlf`
```xml
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<xliff version="1.0">
	<file source-language="en" datatype="plaintext" original="messages" date="2018-12-17T10:52:39Z" product-name="site_package">
		<header/>
		<body>
			<trans-unit id="issue-43.element.Person.properties.label">
				<source>[EN] Person</source>
			</trans-unit>
			<trans-unit id="issue-43.element.Example.properties.label">
				<source>[EN] Example</source>
			</trans-unit>

			<!-- first iteration (original)-->
			<trans-unit id="issue-43.element.RepeatableContainer-1.properties.label">
				<source>[EN] Original Repeatable Container</source>
			</trans-unit>
			<trans-unit id="issue-43.element.RepeatableContainer-1.0.Person.properties.label">
				<source>[EN] 1. Person</source>
			</trans-unit>

			<!-- second iteration -->
			<trans-unit id="issue-43.element.RepeatableContainer-1.1.properties.label">
				<source>[EN] 1. Repetition</source>
			</trans-unit>
			<trans-unit id="issue-43.element.RepeatableContainer-1.1.Person.properties.label">
				<source>[EN] 2. Person</source>
			</trans-unit>
		</body>
	</file>
</xliff>
```

`EXT:site_package/Resources/Private/Language/de.issue-43.xlf`
```xml
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<xliff version="1.0">
	<file source-language="en" datatype="plaintext" original="messages" date="2018-12-17T10:52:39Z" product-name="site_package">
		<header/>
		<body>
			<trans-unit id="issue-43.element.Person.properties.label">
				<target>[DE] Person</target>
			</trans-unit>
			<trans-unit id="issue-43.element.Example.properties.label">
				<target>[DE] Beispiel</target>
			</trans-unit>
			<!-- first iteration (original)-->
			<trans-unit id="issue-43.element.RepeatableContainer-1.0.properties.label">
				<target>[DE] Originaler Wiederholbarer Behälter</target>
			</trans-unit>
			<trans-unit id="issue-43.element.RepeatableContainer-1.0.Person.properties.label">
				<target>[DE] 1. Person</target>
			</trans-unit>
			<!-- second iteration -->
			<trans-unit id="issue-43.element.RepeatableContainer-1.1.properties.label">
				<target>[DE] 1. Wiederholung</target>
			</trans-unit>
			<trans-unit id="issue-43.element.RepeatableContainer-1.1.Person.properties.label">
				<target>[DE] 2. Person</target>
			</trans-unit>
		</body>
	</file>
</xliff>
```

With this example, each copy just created would get the labels from the original (see xlf).

If you then switch to another page (e.g. summary), each repetition accesses its specific labels. This label is retained when you switch back to the page.

More information: https://docs.typo3.org/c/typo3/cms-form/12.4/en-us/I/Concepts/FrontendRendering/Index.html#translation
